/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./public/**/*.{html,js}",
    "./views/**/*.{html,js}",
    "./*.html",
    "./public/index.html"
  ],
  safelist: [
    'bg-white/95',
    'backdrop-blur-md',
    'border-b',
    'border-gray-200',
    'sticky',
    'top-0',
    'z-50',
    'transition-all',
    'duration-300',
    'hover:scale-105',
    'hidden',
    'sm:flex',
    'items-center',
    'space-x-4',
    'lg:space-x-6',
    'text-gray-700',
    'hover:text-gray-900',
    'font-medium',
    'duration-200',
    'sm:hidden',
    'p-2',
    'rounded-md',
    'text-gray-700',
    'hover:text-gray-900',
    'hover:bg-gray-100',
    'bg-gradient-to-br',
    'from-blue-50',
    'via-indigo-50',
    'to-purple-50',
    'py-12',
    'sm:py-16',
    'lg:py-20',
    'text-center',
    'text-3xl',
    'sm:text-4xl',
    'lg:text-5xl',
    'font-bold',
    'text-gray-900',
    'mb-6',
    'hover-fade-up',
    'text-lg',
    'sm:text-xl',
    'text-gray-600',
    'mb-8',
    'sm:mb-12',
    'max-w-2xl',
    'mx-auto',
    'hover-slide-left',
    'max-w-4xl',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-3',
    'gap-4',
    'mb-6',
    'w-full',
    'text-center',
    'py-3',
    'text-base',
    'sm:text-lg',
    'px-6',
    'sm:px-8',
    'text-2xl',
    'sm:text-3xl',
    'font-bold',
    'mb-8',
    'sm:mb-12',
    'grid-responsive',
    'text-3xl',
    'mb-4',
    'hover-pulse',
    'text-lg',
    'sm:text-xl',
    'font-semibold',
    'mb-3',
    'mb-4',
    'bg-gradient-to-r',
    'from-blue-50',
    'to-indigo-50',
    'rounded-lg',
    'p-3',
    'border-l-4',
    'border-blue-400',
    'text-sm',
    'text-blue-800',
    'from-green-50',
    'to-emerald-50',
    'border-green-400',
    'text-green-800',
    'from-purple-50',
    'to-pink-50',
    'border-purple-400',
    'text-purple-800',
    'from-gray-50',
    'to-blue-50',
    'rounded-full',
    'w-12',
    'h-12',
    'sm:w-16',
    'sm:h-16',
    'flex',
    'justify-center',
    'mx-auto',
    'mb-4',
    'text-white',
    'hover-float',
    'hover-bounce',
    'hover-rotate',
    'bg-gray-900',
    'text-white',
    'py-12',
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-4',
    'gap-8',
    'mb-8',
    'text-lg',
    'font-semibold',
    'mb-4',
    'text-gray-400',
    'text-sm',
    'hover:text-white',
    'transition-colors',
    'border-t',
    'border-gray-700',
    'pt-8',
    'mt-4'
  ],
  theme: {
    extend: {
      fontFamily: {
        'inter': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
        'slide-in-left': 'slideInLeft 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
        'slide-in-right': 'slideInRight 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards',
        'pulse': 'pulse 1.2s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        'float': 'float 2.5s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        'shake': 'shake 0.6s cubic-bezier(0.36, 0, 0.66, 1) ease-in-out',
        'bounce': 'bounce 1.2s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        'rotate': 'rotate 2.5s cubic-bezier(0.4, 0, 0.2, 1) infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.08)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-3px)' },
          '75%': { transform: 'translateX(3px)' },
        },
        bounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
}
